owner: hakai-it # GitHub username
repo: hakai-datasets-upptime
sites: # List of endpoints to track
  - name: HakaiADCPTimeSeriesProfileProvisional
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiADCPTimeSeriesProfileProvisional.htmlTable?time&time<=now-1week&distinct()
  - name: HakaiSewardBoL5min
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiSewardBoL5min.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiQuadraBoLResearch
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraBoLResearch.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiBaynesSoundBoL5min
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiBaynesSoundBoL5min.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiKetchikanBoLResearch
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiKetchikanBoLResearch.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiSitkaBoL5min
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiSitkaBoL5min.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiADCPTimeSeriesProfileProvisional
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiADCPTimeSeriesProfileProvisional.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiWaterPropertiesInstrumentProfileProvisional
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiWaterPropertiesInstrumentProfileProvisional.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiMooredTimeSeriesResearch
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiMooredTimeSeriesResearch.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiCalvertCP1TideGauge
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiCalvertCP1TideGauge.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiQuadraBoL5min
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraBoL5min.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiKodiakBoL5min
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiKodiakBoL5min.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiKetchikanBoL5min
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiKetchikanBoL5min.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiKCBuoyResearch
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiKCBuoyResearch.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiPruthDockProvisional
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiPruthDockProvisional.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiQuadraWeather5min
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraWeather5min.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiQU5MMooringProvisional
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiQU5MMooringProvisional.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiWaterPropertiesInstrumentProfileResearch
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiWaterPropertiesInstrumentProfileResearch.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiKCBuoy1hour
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiKCBuoy1hour.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiSitkaBoLResearch
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiSitkaBoLResearch.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiQuadraLimpet5min
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraLimpet5min.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiColumbiaFerryResearch
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiColumbiaFerryResearch.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: HakaiPruthMooringProvisional
    url: https://catalogue.hakai.org/erddap/tabledap/HakaiPruthMooringProvisional.htmlTable?time&time<=now-1week&distinct()
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /hakai-datasets-uptime
  logoUrl: https://hakai.org/wp-content/themes/HakaiInstitute/images/logo.svg
  name: Hakai ERDDAP Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/hakaiInstitute/hakai-datasets-upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"

# Upptime also supports notifications, assigning issues, and more

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "* */12 * * *"
