owner: HakaiInstitute
repo: hakai-datasets-upptime
sites:
- name: 'catalogue.hakai.org - HakaiADCPTimeSeriesProfileProvisional: Data Access
    Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiADCPTimeSeriesProfileProvisional.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiADCPTimeSeriesProfileProvisional: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiADCPTimeSeriesProfileProvisional.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiMooredTimeSeriesResearch: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiMooredTimeSeriesResearch.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiMooredTimeSeriesResearch: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiMooredTimeSeriesResearch.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiWaterPropertiesInstrumentProfileProvisional: Data
    Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiWaterPropertiesInstrumentProfileProvisional.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiWaterPropertiesInstrumentProfileProvisional: Download
    test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiWaterPropertiesInstrumentProfileProvisional.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiWaterPropertiesInstrumentProfileResearch: Data
    Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiWaterPropertiesInstrumentProfileResearch.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiWaterPropertiesInstrumentProfileResearch: Download
    test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiWaterPropertiesInstrumentProfileResearch.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiQuadraBoLResearch: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraBoLResearch.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiQuadraBoLResearch: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraBoLResearch.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiSitkaBoLResearch: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiSitkaBoLResearch.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiSitkaBoLResearch: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiSitkaBoLResearch.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiKetchikanBoLResearch: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKetchikanBoLResearch.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiKetchikanBoLResearch: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKetchikanBoLResearch.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiQuadraWeather5min: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraWeather5min.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiQuadraWeather5min: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraWeather5min.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiQuadraLimpet5min: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraLimpet5min.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiQuadraLimpet5min: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraLimpet5min.htmlTable?&time>now-1minute
- expectedStatusCodes:
  - 200
  name: 'catalogue.hakai.org - HakaiQuadraLimpet5min: Real-time now-1day'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraLimpet5min.htmlTable?time&time>=now-1day
- name: 'catalogue.hakai.org - HakaiPruthMooringProvisional: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiPruthMooringProvisional.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiPruthMooringProvisional: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiPruthMooringProvisional.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiPruthDockProvisional: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiPruthDockProvisional.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiPruthDockProvisional: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiPruthDockProvisional.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiQU5MMooringProvisional: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQU5MMooringProvisional.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiQU5MMooringProvisional: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQU5MMooringProvisional.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiBaynesSoundBoL5min: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiBaynesSoundBoL5min.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiBaynesSoundBoL5min: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiBaynesSoundBoL5min.htmlTable?&time>now-1minute
- expectedStatusCodes:
  - 200
  name: 'catalogue.hakai.org - HakaiBaynesSoundBoL5min: Real-time now-1day'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiBaynesSoundBoL5min.htmlTable?time&time>=now-1day
- name: 'catalogue.hakai.org - HakaiQuadraBoL5min: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraBoL5min.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiQuadraBoL5min: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraBoL5min.htmlTable?&time>now-1minute
- expectedStatusCodes:
  - 200
  name: 'catalogue.hakai.org - HakaiQuadraBoL5min: Real-time now-1day'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiQuadraBoL5min.htmlTable?time&time>=now-1day
- name: 'catalogue.hakai.org - HakaiKodiakBoL5min: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKodiakBoL5min.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiKodiakBoL5min: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKodiakBoL5min.htmlTable?&time>now-1minute
- expectedStatusCodes:
  - 200
  name: 'catalogue.hakai.org - HakaiKodiakBoL5min: Real-time now-1day'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKodiakBoL5min.htmlTable?time&time>=now-1day
- name: 'catalogue.hakai.org - HakaiSewardBoL5min: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiSewardBoL5min.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiSewardBoL5min: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiSewardBoL5min.htmlTable?&time>now-1minute
- expectedStatusCodes:
  - 200
  name: 'catalogue.hakai.org - HakaiSewardBoL5min: Real-time now-1day'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiSewardBoL5min.htmlTable?time&time>=now-1day
- name: 'catalogue.hakai.org - HakaiKetchikanBoL5min: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKetchikanBoL5min.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiKetchikanBoL5min: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKetchikanBoL5min.htmlTable?&time>now-1minute
- expectedStatusCodes:
  - 200
  name: 'catalogue.hakai.org - HakaiKetchikanBoL5min: Real-time now-1day'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKetchikanBoL5min.htmlTable?time&time>=now-1day
- name: 'catalogue.hakai.org - HakaiSitkaBoL5min: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiSitkaBoL5min.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiSitkaBoL5min: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiSitkaBoL5min.htmlTable?&time>now-1minute
- expectedStatusCodes:
  - 200
  name: 'catalogue.hakai.org - HakaiSitkaBoL5min: Real-time now-1day'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiSitkaBoL5min.htmlTable?time&time>=now-1day
- name: 'catalogue.hakai.org - HakaiKCBuoy1hour: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKCBuoy1hour.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiKCBuoy1hour: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKCBuoy1hour.htmlTable?&time>now-1minute
- expectedStatusCodes:
  - 200
  name: 'catalogue.hakai.org - HakaiKCBuoy1hour: Real-time now-1day'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKCBuoy1hour.htmlTable?time&time>=now-1day
- name: 'catalogue.hakai.org - HakaiKCBuoyResearch: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKCBuoyResearch.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiKCBuoyResearch: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiKCBuoyResearch.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiColumbiaFerryResearch: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiColumbiaFerryResearch.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiColumbiaFerryResearch: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiColumbiaFerryResearch.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiCalvertCP1TideGauge: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiCalvertCP1TideGauge.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiCalvertCP1TideGauge: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiCalvertCP1TideGauge.htmlTable?&time>now-1minute
- name: 'catalogue.hakai.org - HakaiBamfieldBoL5min: Data Access Form'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiBamfieldBoL5min.html
- expectedStatusCodes:
  - 200
  - 201
  - 404
  name: 'catalogue.hakai.org - HakaiBamfieldBoL5min: Download test'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiBamfieldBoL5min.htmlTable?&time>now-1minute
- expectedStatusCodes:
  - 200
  name: 'catalogue.hakai.org - HakaiBamfieldBoL5min: Real-time now-1day'
  url: https://catalogue.hakai.org/erddap/tabledap/HakaiBamfieldBoL5min.htmlTable?time&time>=now-1day
status-website:
  baseUrl: /hakai-datasets-upptime
  introMessage: "This is a sample status page which uses **real-time** data from our\
    \ [GitHub repository](https://github.com/hakaiInstitute/hakai-datasets-upptime).\
    \ No server required \u2014 just GitHub Actions, Issues, and Pages. [**Get your\
    \ own for free**](https://github.com/upptime/upptime)"
  introTitle: '**Upptime** is the open-source uptime monitor and status page, powered
    entirely by GitHub.'
  logoUrl: https://hakai.org/wp-content/themes/HakaiInstitute/images/logo.svg
  metaTags:
  - content: dark light
    name: color-scheme
  - content: noindex
    name: robots
  name: Hakai ERDDAP Upptime
  navbar:
  - href: /
    title: Status
  - href: https://github.com/$OWNER/$REPO
    title: GitHub
  theme: ocean
user-agent: HakaiInstitute
